### ISSUE TITLE
No needed project files available

### ISSUE THREAD

**Issue by RLEXBuilding** [AntiLaby/AntiLaby#15]
For AntiLaby is no pom.xml or build.gradle file available. 
=> Please fix this. 👍

**Comment by heisluft** [comment]
Thank you for this idea of iprovement, AntiLaby is not a maven or gradle project at this time. I consider this issue only a minor improvement, as at this time, I am focused on the new Language system and Nathan on cleaning up and mproving the API.

**Comment by RLEXBuilding** [comment]
Okay 📦
