### ISSUE TITLE
Subcommand System

### ISSUE THREAD

**Issue by DeepRobin** [AntiLaby/AntiLaby#21]
You can make your plugin more object-orientated. You can add a subcommand system with an abstract packagePrivate class called Subcommand.

Example: /antilaby subCommand

**Comment by heisluft** [comment]
Commands are @NathanNr's thing

**Comment by NathanNr** [comment]
I may add it, if we add more subcommands. Currently it has a low priority.

**Comment by heisluft** [comment]
We already fixed this 🤦‍♂️
