### ISSUE TITLE
Fix pre-1.9 locale issues

### ISSUE THREAD

**Issue by heisluft** [AntiLaby/AntiLaby#23]

**Comment by NathanNr** [comment]
Error message (Minecraft version 1.8.8, AntiLaby vpre-2.0):

> [Server thread/ERROR]: [AntiLaby/Spigot] Plugin AntiLaby vpre-2.0 has failed to register events for class com.github.antilaby.antilaby.events.PlayerJoin because org/bukkit/event/player/PlayerLocaleChangeEvent does not exist.
