### ISSUE TITLE
Notify operators about AntiLaby player kicks

### ISSUE THREAD

**Issue by NathanNr** [AntiLaby/AntiLaby#29]
Add a feature to notify players with an specified permission about player kicks or bans of AntiLaby.
Suggested by [TheGamer7500](https://www.spigotmc.org/members/thegamer7500.191548/) [here](https://www.spigotmc.org/resources/21347/reviews#review-196060-191548).

**Comment by NathanNr** [comment]
Todo: add the notification message to the language system

**Comment by heisluft** [comment]
Implemented
