### ISSUE TITLE
1.13 support.

### ISSUE THREAD

**Issue by TheIntelloBox** [AntiLaby/AntiLaby#30]
Hey.

AntiLaby doesn't work with Minecraft 1.13. Could you add the support of this version ? :)

Thanks ! :D

**Comment by heisluft** [comment]
Please note that there is no official stable version of Spigot for 1.13. Malfunctioning plugins can thus be a result of a bug in the Bukkit / Spigot codebase. You can either send me a crashreport / a log file so I can investigate or wait until a stable 1.13 release is there and see if the issue persists.

Kind regards

**Comment by heisluft** [comment]
Neither Forge or LabyMod are out for 1.13. I'll close this issue
