### ISSUE TITLE
Implement LabyModPlayerBan

### ISSUE THREAD

**Issue by NathanNr** [AntiLaby/AntiLaby#33]
Add a basic ban system to ban players who are using LabyMod permanently. The use of advantaged ban systems should be allowed by using a custom ban command with variables.

**Comment by NathanNr** [comment]
Todo:
* Read ban message from the language files
* Testing

**Comment by NathanNr** [comment]
Todo: Read ban message from the language files

**Comment by DeepRobin** [comment]
It were cleverer to add an API where every Developer can add own things

**Comment by NathanNr** [comment]
It is possible to use a custom ban command so you are able to use a custom ban systen.
