### ISSUE TITLE
How did you made the overlays?

### ISSUE THREAD

**Issue by jqshuv** [AntiLaby/AntiLaby#40]
Hey, I'm programming Minecraft plugins myself and I wanted to know how you made these fade in.

**Comment by NathanNr** [comment]
Hey, if you mean these messages at the top right: https://www.spigotmc.org/attachments/antilaby_1_10_panorama-png.299412/
They are part of the LabyMod client and not part of vanilla Minecraft.
https://github.com/AntiLaby/AntiLaby/blob/84afc676293c2a2ce40fe20088060e3179c2a190/src/main/java/com/github/antilaby/antilaby/util/CraftFeatureProvider.java#L99

**Comment by hypnore** [comment]
Yes, thanks
